services:
    - type: web
      name: yt-summary-api
      env: python
      rootDir: server
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
      autoDeploy: true
      plan: free
      envVars:
          - key: OPENAI_API_KEY
            sync: false
